service: song-contest-rater
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  stage: dev
  environment:
    SONG_CONTEST_RATER_ACTS_TABLE: '${self:custom.tableNames.acts}-${opt:stage, self:provider.stage}'
    SONG_CONTEST_RATER_COMPETITIONS_TABLE: '${self:custom.tableNames.competitions}-${opt:stage, self:provider.stage}'
    SONG_CONTEST_RATER_DYNAMODB_ENDPOINT: ${self:custom.endpoints.dynamodb}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: '*'

plugins:
  - serverless-bundle
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-pseudo-parameters

custom:
  bundle:
    linting: false
  dynamodb:
    start:
      migrate: true
    stages:
      - local
  tableNames:
    acts: 'acts'
    competitions: 'competitions'
  endpoints:
    dynamodb: 'http://localhost:8000'

functions:
  - ${file(infrastructure/act/functions.yml)}
  - ${file(infrastructure/competition/functions.yml)}

resources:
  - ${file(infrastructure/act/resources.yml)}
  - ${file(infrastructure/competition/resources.yml)}
  - ${file(infrastructure/shared/resources.yml)}
