createAct:
  handler: src/act/act-gateway.createAct
  events:
    - http:
        path: acts
        method: post
        cors: true
        authorizer:
          type: COGNITO_USER_POOLS
          authorizerId:
            Ref: ApiGatewayAdminAuthorizer
listActs:
  handler: src/act/act-gateway.listActs
  events:
    - http:
        path: acts
        method: get
        cors: true
        authorizer:
          type: COGNITO_USER_POOLS
          authorizerId:
            Ref: ApiGatewayAuthorizer
getAct:
  handler: src/act/act-gateway.getAct
  events:
    - http:
        path: acts/{id}
        method: get
        cors: true
        authorizer:
          type: COGNITO_USER_POOLS
          authorizerId:
            Ref: ApiGatewayAuthorizer
updateAct:
  handler: src/act/act-gateway.updateAct
  events:
    - http:
        path: acts/{id}
        method: put
        cors: true
        authorizer:
          type: COGNITO_USER_POOLS
          authorizerId:
            Ref: ApiGatewayAdminAuthorizer
deleteAct:
  handler: src/act/act-gateway.deleteAct
  events:
    - http:
        path: acts/{id}
        method: delete
        cors: true
        authorizer:
          type: COGNITO_USER_POOLS
          authorizerId:
            Ref: ApiGatewayAdminAuthorizer
