createAct:
  handler: src/act/act-gateway.createAct
  events:
    - http:
        path: acts
        method: post
        cors: true
        authorizer:
          type: COGNITO_USER_POOLS
          authorizerId:
            Ref: ApiGatewayAuthorizer
listActs:
  handler: src/act/act-gateway.listActs
  events:
    - http:
        path: acts
        method: get
        cors: true
        request:
          template:
            application/json: >
              {
                "ids" : "$input.params('ids')"
              }
getAct:
  handler: src/act/act-gateway.getAct
  events:
    - http:
        path: acts/{id}
        method: get
        cors: true
updateAct:
  handler: src/act/act-gateway.updateAct
  events:
    - http:
        path: acts/{id}
        method: put
        cors: true
        authorizer:
          type: COGNITO_USER_POOLS
          authorizerId:
            Ref: ApiGatewayAuthorizer
deleteAct:
  handler: src/act/act-gateway.deleteAct
  events:
    - http:
        path: acts/{id}
        method: delete
        cors: true
        authorizer:
          type: COGNITO_USER_POOLS
          authorizerId:
            Ref: ApiGatewayAuthorizer
