import { attribute, autoGeneratedHashKey, table } from '@aws/dynamodb-data-mapper-annotations';

@table(process.env.SONG_CONTEST_RATER_ACTS_TABLE)
export class ActDocument {
  @autoGeneratedHashKey()
  id: string;
  @attribute()
  artistName: string;
  @attribute()
  songName: string;
}

export const defaultActDocument: ActDocument = {
  id: '84ce3ed6-a479-4ba4-86e1-d053638fd8a1',
  artistName: 'John Document',
  songName: 'I am John Doocument',
};
