import { attribute, autoGeneratedHashKey, table } from '@aws/dynamodb-data-mapper-annotations';

@table(process.env.SONG_CONTEST_RATER_ACTS_TABLE)
export class ActDocument {
  @autoGeneratedHashKey()
  id: string;
  @attribute()
  artistName: string;
  @attribute()
  songName: string;
}
